#!/bin/bash
set -e
tag=vcpkg-cache-v1
# Always pull from the main qpdf repo, not a fork.
repo=qpdf/qpdf
latest=$(gh release view --repo $repo $tag \
            --json assets --jq '.assets[]|(.updatedAt + " " + .name)' | \
             sort -r | head -n 1 | awk '{print $NF}')
gh release download --repo $repo $tag -p $latest
mv $latest vcpkg.zip
